name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
      - name: Setup VOICEVOX Core for CI
        run: |
          # VOICEVOX Core wheelをダウンロード
          curl -L -o voicevox_core-0.16.0-cp310-abi3-manylinux_2_34_x86_64.whl \
            https://github.com/VOICEVOX/voicevox_core/releases/download/0.16.0/voicevox_core-0.16.0-cp310-abi3-manylinux_2_34_x86_64.whl
          
          # pyproject.tomlのパスを現在のディレクトリ基準に書き換え
          sed -i 's|voicevox-core = { path = "voicevox_core-0.16.0-cp310-abi3-manylinux_2_34_x86_64.whl" }|voicevox-core = { path = "./voicevox_core-0.16.0-cp310-abi3-manylinux_2_34_x86_64.whl" }|' pyproject.toml
      - name: Install dependencies
        run: uv sync --group=dev
      - name: Run lint
        run: uv run ruff check src

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
      - name: Setup VOICEVOX Core for CI
        run: |
          # VOICEVOX Core wheelをダウンロード
          curl -L -o voicevox_core-0.16.0-cp310-abi3-manylinux_2_34_x86_64.whl \
            https://github.com/VOICEVOX/voicevox_core/releases/download/0.16.0/voicevox_core-0.16.0-cp310-abi3-manylinux_2_34_x86_64.whl
          
          # pyproject.tomlのパスを現在のディレクトリ基準に書き換え
          sed -i 's|voicevox-core = { path = "voicevox_core-0.16.0-cp310-abi3-manylinux_2_34_x86_64.whl" }|voicevox-core = { path = "./voicevox_core-0.16.0-cp310-abi3-manylinux_2_34_x86_64.whl" }|' pyproject.toml
      - name: Install dependencies
        run: uv sync --group=dev
      - name: Run tests
        run: uv run pytest
